# Generated by Django 6.0.1 on 2026-02-16 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrada', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='codigo',
            field=models.CharField(default='E000', max_length=10),
        ),
        migrations.AddField(
            model_name='entrada',
            name='fecha_venta',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='asiento',
            field=models.CharField(max_length=5),
        ),
    ]
