<<<<<<< HEAD
# Generated by Django 6.0.1 on 2026-02-24 00:14
=======
# Generated by Django 6.0.2 on 2026-02-23 15:33
>>>>>>> fa15de0d684b09b0734c34e2a24de3f417f2a78c

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrada', '0002_entrada_codigo_entrada_fecha_venta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='precio_final',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
