# Generated by Django 6.0.1 on 2026-02-16 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcion', '0001_initial'),
        ('pelicula', '0005_funcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcion',
            name='pelicula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funciones_funcion', to='pelicula.pelicula'),
        ),
    ]
