# Generated by Django 6.0.1 on 2026-02-01 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pelicula', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='genero',
            field=models.CharField(choices=[('accion', 'Acción'), ('comedia', 'Comedia'), ('drama', 'Drama'), ('terror', 'Terror'), ('fantasia', 'Fantasía'), ('romance', 'Romance'), ('suspenso', 'Suspenso')], default='accion', max_length=20),
        ),
    ]
