# Generated by Django 6.0.1 on 2026-02-16 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pelicula', '0002_pelicula_genero'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='duracion_min',
            field=models.IntegerField(default=0),
        ),
    ]
