# Generated by Django 6.0.1 on 2026-02-16 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pelicula', '0003_pelicula_duracion_min'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pelicula',
            name='duracion',
        ),
    ]
