# Generated by Django 6.0.1 on 2026-02-16 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pelicula', '0004_remove_pelicula_duracion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=20)),
                ('fecha_hora', models.DateTimeField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funciones_pelicula', to='pelicula.pelicula')),
            ],
        ),
    ]
