# Generated by Django 6.0.1 on 2026-02-24 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pelicula', '0005_funcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='SnackCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=50)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='genero',
            field=models.CharField(choices=[('accion', 'Acción'), ('comedia', 'Comedia'), ('drama', 'Drama'), ('terror', 'Terror'), ('fantasia', 'Fantasía'), ('romance', 'Romance'), ('suspenso', 'Suspenso'), ('aventura', 'Aventura')], default='accion', max_length=20),
        ),
    ]
